### ISSUE TITLE
what's your gnome-shell theme?

### ISSUE THREAD

**Issue by wotmshuaisi** [rdnlsmith/vscode-arc-theme#1]
can you tell me your gnome-shell theme and taskbar extensions

**Comment by SolarLiner** [comment]
Currently I'm using the Adapta theme with Papirus icons. Extensions are Dynamic Panel Transparency, GitHub Notifications, TopIcons Plus and Frippery Move Clock. On the screenshots I used Dash to Panel but those were on my desktop PC; I disabled it on my laptop for space issues.

**Comment by SolarLiner** [comment]
(Also closing as it's not an issue per se)
