### ISSUE TITLE
How did you get the Ubuntu Theme in your Integrated Terminal

### ISSUE THREAD

**Issue by steve3p0** [rdnlsmith/vscode-arc-theme#18]
How did you get the Ubuntu Theme in your Integrated Terminal?

**Comment by rdnlsmith** [comment]
The Yaru and Yaru Dark themes contain the color keys below. You can also put them in your `settings.json` under `"workbench.colorCustomizations"` if you want to use an Ubuntu-like terminal with some other theme.

To make it exactly like the Ubuntu terminal, I also set `"terminal.integrated.fontFamily": "Ubuntu Mono"` and `"terminal.integrated.fontSize": 16` in `settings.json` (I don't think you can put font settings in a theme).

Hope this helps! 

```json
"terminal.background": "#300a24",
"terminal.ansiBlack": "#000000",
"terminal.ansiBlue": "#0000aa",
"terminal.ansiBrightBlack": "#555555",
"terminal.ansiBrightBlue": "#5555ff",
"terminal.ansiBrightCyan": "#55ffff",
"terminal.ansiBrightGreen": "#55ff55",
"terminal.ansiBrightMagenta": "#ff55ff",
"terminal.ansiBrightRed": "#ff5555",
"terminal.ansiBrightWhite": "#ffffff",
"terminal.ansiBrightYellow": "#ffff55",
"terminal.ansiCyan": "#00aaaa",
"terminal.ansiGreen": "#00aa00",
"terminal.ansiMagenta": "#aa00aa",
"terminal.ansiRed": "#aa0000",
"terminal.ansiWhite": "#aaaaaa",
"terminal.ansiYellow": "#aa5500",
```

**Comment by steve3p0** [comment]
Thank you!!!
