### ISSUE TITLE
Add support for inputOption.activeBackground

### ISSUE THREAD

**Issue by miguelsolorio** [rdnlsmith/vscode-arc-theme#21]
VS Code will be introducing a new token color, `inputOption.activeBackground`, in the July release (1.37). This color is for showing when a button toggle is active (search, find, terminal find, etc.). It also re-uses `focusBorder` but in the `Arc Dark` theme the focus color is set to transparent, which means the new token color is also transparent. See below where you can't tell which item is "active", please consider adding support for this. You can test this by using the [Insiders version](https://code.visualstudio.com/insiders/), which already adds this.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/35271042/62478333-b18b8e00-b75f-11e9-846f-973098d1cd9b.png">

**Comment by rdnlsmith** [comment]
Thanks for the heads-up!

The Arc theme (and Yaru themes) is currently dependent on [tyriar/vscode-theme-generator](https://github.com/Tyriar/vscode-theme-generator), so I’ll have to see about getting it added there when I have time. I’m also exploring writing my own generator which could take an actual GTK theme as input. Either way, I intend to support this, but it could be a few weeks.

**Comment by rdnlsmith** [comment]
@misolori thanks for your patience on this. I loaded the Arc Dark theme in the latest VS Code 1.46.1 and it looks to me like the selected toggle buttons are visible. Can you confirm this? Or am I misunderstanding the problem?

![Screenshot from 2020-06-27 15-53-12](https://user-images.githubusercontent.com/4039042/85931034-1deb1080-b88f-11ea-9502-163f02460470.png)

**Comment by miguelsolorio** [comment]
Hmm...I just tested the Arc Dark theme from the marketplace and am seeing something different:

![image](https://user-images.githubusercontent.com/35271042/86031580-df6a6880-b9ea-11ea-81e7-a0dedab7395a.png)

**Comment by rdnlsmith** [comment]
Are you using `solarliner.linux-themes`? That extension matches your screenshot on my computer. However, the extension changed hands in 2018 and I re-published it as `rdnlsmith.linux-themes`.

**Comment by miguelsolorio** [comment]
Ah, I've been referencing `solarliner.linux-themes`. It is confusing then to have both themes published with the same name:

![image](https://user-images.githubusercontent.com/35271042/86034855-33c41700-b9f0-11ea-9d61-d1eff1fb357f.png)

So is there no way to update the `solarliner.linux-themes` theme?

**Comment by rdnlsmith** [comment]
There wasn’t a way for @SolarLiner to give me publishing rights to the `solarliner.linux-themes` extension without also giving me access to his whole `solarliner` account in the VS Code marketplace. We decided at the time that the best way forward was to consider `solarliner.linux-themes` deprecated and re-publish under my own account.

We talked about adding a depreciation notice to the old extension, but he didn’t get around to it for a while, and by then people were already finding the new extension so we didn’t think it would be a big deal one way or the other.

Anyways, the bottom line is that if you want to receive updates, please uninstall `solarliner.linux-themes` and install `rdnlsmith.linux-themes`!

If you really want to stick with the theme you have for any reason, you can also just [override this one key in your settings](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme) to fix the highlighting issue.

**Comment by miguelsolorio** [comment]
In this case I'll close this issue since there's nothing else to do. Thanks for the response!
