### ISSUE TITLE
Const and Let can have a different colour?

### ISSUE THREAD

**Issue by max-programming** [rdnlsmith/vscode-arc-theme#23]
I love this theme. But there is one difference between this and other popular themes. Some of the popular themes and even the default theme have a different colour for const and let in JavaScript

![image](https://user-images.githubusercontent.com/51731966/85683229-a8ded600-b6ea-11ea-8722-ff00c36f3f14.png)
![image](https://user-images.githubusercontent.com/51731966/85683454-dcb9fb80-b6ea-11ea-9390-f614240cd049.png)

It would be a lot nicer if this theme has this feature. Thanks!

**Comment by rdnlsmith** [comment]
Hi, thanks for the issue!

Several of the themes in this repo (Arc Dark, Yaru, Yaru Dark, the unreleased Elementary theme) are built on [tyriar/vscode-theme-generator](https://github.com/Tyriar/vscode-theme-generator/), which as part of its design philosophy provides a limited set of keys for syntax colors. I'd prefer not to deviate from that for now.

However, you can customize it easily in your `settings.json`! The snippet below would make JavaScript constants red when using the Arc Dark theme. You can leave off the `:javascript` part if you want it to apply to constants in all languages which currently provide [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide).

```js
"editor.semanticTokenColorCustomizations": {
  "[Arc Dark]": {
    "enabled": true,
    "rules": {
      "variable.readonly:javascript": "#ff0000"
    }
  }
}
```

**Comment by max-programming** [comment]
WOW. Thanks for the solution!
