### ISSUE TITLE
The `import` keyword in Python has different color

### ISSUE THREAD

**Issue by hongquan** [rdnlsmith/vscode-arc-theme#6]
![example](https://raw.githubusercontent.com/SolarLiner/vscode-arc-theme/master/res/screen_ambiance.png)

**Comment by SolarLiner** [comment]
I've used the theme to test it out and it didn't shock me all that much. Would the 'import' keyword need to be the same color as the 'from' keyword?

**Comment by hongquan** [comment]
> Would the 'import' keyword need to be the same color as the 'from' keyword?

I wonder why do you have that question? Aren't `import` and `from` keywords? Doesn't it make sense that the style should be consistent, all the keyword should be in the same color?

**Comment by SolarLiner** [comment]
The syntax coloring comes from Base16, so the coloring rules comes from it. I guess the thought process was that when `from` is used, the `import` keyword is only secondary to it, as in one level below (like, digging *inside* the module).

I'll change it though.

**Comment by hongquan** [comment]
I noticed that VS Code seems to have convention that secondary keyword has different style from the primary one. So you can ignore this request.

![screenshot from 2017-11-10 09-37-29](https://user-images.githubusercontent.com/314607/32640356-e2bf9f82-c5fa-11e7-82db-b3597e28867a.png)
